### ISSUE TITLE
Dont work on Heroku

### ISSUE THREAD

**Issue by Jaglag** [rcs/hubot-epichal#1]
Hi there,

i added your script to heroku and set 2 env. variables on the config REDISTOGO_URL, REDISCLOUD_URL

When i try to start the bot i get this error:

(UTC)] ERROR Unable to load /app/node_modules/hubot-epichal/src/epichal: Error:
Cannot find module 'redis'

do i need to "install" redis too??? its already on heroku?

http://prntscr.com/6l6yax

**Comment by rcs** [comment]
Sorry about your problems! I've been running this on Heroku, so it took me a minute to figure out.

The dependency build out was assuming your `hubot` package has a redis dependency listed on it.

I've fixed this in the most recent commit 1d8fb1ab9ac4a5d45ec3b35db11003d854862d48 and it would be great if you could give this another try.

Please let me know if that works out for you, or if you think there's a better way that should be handled.

**Comment by Jaglag** [comment]
Tyvm rcs!
very fast response atm its working and already response:

[18:11:27] [~Jaglag]: hi Butlerz
[18:11:32] [~Jaglag]: Butlerz test
[18:11:33] [@Butlerz]: hi Butlerz

then lets see how long it will take till the free 25mb on redis running out XD

**Comment by rcs** [comment]
happy to hear it worked out!
